Admin can view his articles
CraftAcademy/newsroom_jan_21_client_admin pull request #4
Opened 2021-03-08 22:07 UTC by LucasKnudsen

[**PT-Story:**  ](https://www.pivotaltracker.com/story/show/177159993)
### User Story 
``` 
As a journalist
In order to get an overview of my articles
I need the client to display a list of my articles
``` 
## Changes proposed in this pull request: 
* Changes CreateForm into a modal pop up
* Adds some styling
* Creates a dashboard where admin can see all of his/her articles
## What I have learned working on this feature: 
* Targeting the value of a select input field
*

2021-03-08 22:29 UTC, LucasKnudsen commented
We did a kind of code along on this one, going through every step - thereof one-sided commits.. 🤷‍♂️

2021-03-09 08:25 UTC, emtalen requested changes
we should fix the j-tockauth thing before we merge this one

2021-03-09 08:25 UTC, emtalen commented on src/modules/articleModules.js
> +    return true
why do you need to return true?

2021-03-09 10:04 UTC, emtalen approved these changes

2021-03-09 10:04 UTC, merged